checkify/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tasks.urls', namespace='tasks')),
    url(r'', include('forum.urls', namespace='forum')),
    url(r'^users/', include('users.urls', namespace='users')),
]

forum/urls.py
"""Defines URL patterns for tasks."""


from django.conf.urls import url
from . import views


urlpatterns = [


    url(r'^questions/$', views.questions, name='questions'),
    url(r'^questions/(?P<question_id>\d+)/$', views.question, name='question'),
    url(r'^new_question/$', views.new_question, name='new_question'),
    url(r'^new_comment/(?P<question_id>\d+)/$', views.new_comment, name='new_comment'),
    url(r'^edit_comment/(?P<comment_id>\d+)/$',views.edit_comment, name='edit_comment'),
]

forum/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Question(models.Model):
    """A Question the user asks"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Comment(models.Model):
    """Comment under a particular question"""
    question = models.ForeignKey(Question)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'comments'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:] + "..."

forum/forms.py
from django import forms
from .models import Question, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']
        labels = {'text': ''}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

forum/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .forms import QuestionForm, CommentForm
from .models import Question, Comment

# Create your views here.


def questions(request):
        """Displays all the questions"""
        questions = Question.objects.order_by('date_added')
        context = {'questions': questions}
        return render(request, 'forum/questions.html', context)


def question(request, question_id):
        """Displays specific question"""
        question = Question.objects.get(id=question_id)
        comments = question.comment_set.order_by('-date_added')
        context = {'question': question, 'comments': comments}
        return render(request, 'forum/question.html', context)


@login_required
def new_question(request):
        """Asking a new question"""
        if request.method != 'POST':
            # No data submitted; create a blank form.
            form = QuestionForm()
        else:
            # POST data submitted; process data.
            form = QuestionForm(request.POST)
            if form.is_valid():
                new_question = form.save(commit=False)
                new_question.owner = request.user
                new_question.save()
                return HttpResponseRedirect(reverse('forum:questions'))

        context = {'form': form}
        return render(request, 'forum/new_question.html', context)


@login_required
def new_comment(request, question_id):
    """Add a new comment for a particular question."""
    question = Question.objects.get(id=question_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CommentForm()
    else:
        # POST data submitted; process data.
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.question = question
            new_comment.save()
            return HttpResponseRedirect(reverse('forum:question', args=[question_id]))

    context = {'question': question, 'form': form}
    return render(request, 'forum/new_comment.html', context)


@login_required
def edit_comment(request, comment_id):
    """Editing an exsiting comment"""
    comment = Comment.objects.get(id=comment_id)
    question = comment.question

    if request.method != 'POST':
        # Filling up the for with the original comment.
        form = CommentForm(instance=comment)
    else:
        # POST data submitted; process data.
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('forum:question', args=[question.id]))

    context = {'comment': comment, 'question': question, 'form': form}
    return render(request, 'forum/edit_comment.html', context)

forum/templates/forum/edit_comment.html
{% extends "tasks/layout.html" %} 
{% block content %}

<p>
    <a href="{% url 'forum:question' question.id %}">{{ question }}</a>
</p>
<p>Edit comment:</p>

<form action="{% url 'forum:edit_comment' comment.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

forum/templates/forum/new_comment.html
{% extends 'tasks/layout.html' %} 
{% block content %}

<p>
    <a href="{% url 'forum:question' question.id %}">{{ question }}</a>
</p>

<p>Add a new note:</p>
<form action="{% url 'forum:new_comment' question.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}
    <button name="submit">add comment</button>
</form>

{% endblock content %}

forum/templates/forum/new_question.html
{% extends 'tasks/layout.html' %} 

{% block content %}


<p>Add a new question:</p>
<form action="{% url 'forum:new_question' %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}
    <button name="submit">add question</button>
</form>

{% endblock content %}

forum/templates/forum/question.html
{% extends 'tasks/layout.html' %} 


{% block content %}
<p>Question: {{ question }}</p>
<p>Comments:</p>
<p>
    <a href="{% url 'forum:new_comment' question.id %}">add new comment</a>
</p>
<ul>
    {% for comment in comments %}
    <li>
        <p>{{ comment.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ comment.text|linebreaks }}</p>
        <p><a href="{% url 'forum:edit_comment' comment.id %}">edit comment</a></p>
    </li>
    {% empty %}
    <li>
        There are no comments for this question yet.
    </li>
    {% endfor %}
</ul>
{% endblock content %}

forum/templates/forum/questions.html
{% extends "tasks/layout.html" %} 

{% block content %}
<p>Questions</p>

<ul>
    {% for question in questions %}
    <li>
        <a href="{% url 'forum:question' question.id %}">{{ question }}</a>
    </li>
    {% empty %}
    <li>No questions have been added yet.</li>
    {% endfor %} 
</ul>

<a href="{% url 'forum:new_question' %}">Add a new question:</a>

{% endblock content %}