checkify/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tasks.urls', namespace='tasks')),
    url(r'', include('forum.urls', namespace='forum')),
    url(r'^users/', include('users.urls', namespace='users')),
]

forum/urls.py
"""Defines URL patterns for tasks."""


from django.conf.urls import url
from . import views


urlpatterns = [


    url(r'^questions/$', views.questions, name='questions'),
    url(r'^questions/(?P<question_id>\d+)/$', views.question, name='question'),
    url(r'^new_question/$', views.new_question, name='new_question'),
    url(r'^new_comment/(?P<question_id>\d+)/$', views.new_comment, name='new_comment'),
    url(r'^edit_comment/(?P<comment_id>\d+)/$',views.edit_comment, name='edit_comment'),
]

tasks/urls.py
"""Defines URL patterns for tasks."""


from django.conf.urls import url
from . import views


urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_note/(?P<topic_id>\d+)/$', views.new_note, name='new_note'),
    url(r'^edit_note/(?P<note_id>\d+)/$', views.edit_note, name='edit_note'),
]

users/urls.py
"""Defines URL patterns for tasks."""


from django.conf.urls import url
from django.contrib.auth.views import login
from . import views


urlpatterns = [
    # Login
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

tasks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Note(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'notes'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."        

tasks/forms.py
from django import forms
from .models import Topic, Note


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

tasks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .forms import TopicForm, NoteForm
from .models import Topic, Note

# Create your views here.

def index(request):
    """The home page for Checkify"""
    return render(request, 'tasks/index.html')


@login_required
def topics(request):
        """Displays all the Topics"""
        topics = Topic.objects.filter(owner=request.user).order_by('date_added')
        context = {'topics': topics}
        return render(request, 'tasks/topics.html', context)


@login_required
def topic(request, topic_id):
        """Displays all the Topics"""
        topic = Topic.objects.get(id=topic_id)
        if topic.owner != request.user:
            raise Http404
        notes = topic.note_set.order_by('-date_added')
        context = {'topic': topic, 'notes': notes}
        return render(request, 'tasks/topic.html', context)


@login_required
def new_topic(request):
        """Adding a new topic"""
        if request.method != 'POST':
            # No data submitted; create a blank form.
            form = TopicForm()
        else:
            # POST data submitted; process data.
            form = TopicForm(request.POST)
            if form.is_valid():
                new_topic = form.save(commit=False)
                new_topic.owner = request.user
                new_topic.save()
                return HttpResponseRedirect(reverse('tasks:topics'))
        
        context = {'form': form}
        return render(request, 'tasks/new_topic.html', context)


@login_required
def new_note(request, topic_id):
    """Add a new note for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = NoteForm()
    else:
        # POST data submitted; process data.
        form = NoteForm(data=request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.topic = topic
            new_note.save()
            return HttpResponseRedirect(reverse('tasks:topic', args=[topic_id]))
    
    context = {'topic': topic, 'form': form}
    return render(request, 'tasks/new_note.html', context)


@login_required
def edit_note(request, note_id):
    """Editing an exsiting note"""
    note = Note.objects.get(id=note_id)
    topic = note.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Filling up the for with the original note.
        form = NoteForm(instance=note)
    else:
        # POST data submitted; process data.
        form = NoteForm(instance=note, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tasks:topic', args=[topic.id]))

    context = {'note': note, 'topic': topic, 'form': form}
    return render(request, 'tasks/edit_note.html', context)

tasks/templates/tasks/edit_note.html
{% extends "tasks/layout.html" %} 
{% block content %}

<p>
    <a href="{% url 'tasks:topic' topic.id %}">{{ topic }}</a>
</p>
<p>Edit note:</p>

<form action="{% url 'tasks:edit_note' note.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

tasks/templates/tasks/index.html
 {% extends "tasks/layout.html" %}


 {% block content %} 
 
 {% endblock content %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>

<head>
    <title></title>
</head>

<body>
    <p>Checkify</p>
    <p>checkify basically helps you to keep track of what you are learning</p>
    <p>
        <a href="{% url 'tasks:index' %}">Checkify</a> 
        <a href="{% url 'tasks:topics' %}">Tasks</a>
        <a href="{% url 'forum:questions' %}">Questions</a>
            {% if user.is_authenticated %} 
            Hello, {{ user.username }}. 
            <a href="{% url 'users:logout' %}">log out</a>
            {% else %}
        <a href="{% url 'users:login' %}">log in</a>
        <a href="{% url 'users:register' %}">register</a>
            {% endif %}
    </p>
{% block content %} 

{% endblock content %}
</body>

</html>

tasks/templates/tasks/new_note.html
{% extends 'tasks/layout.html' %} 
{% block content %}

<p>
    <a href="{% url 'tasks:topic' topic.id %}">{{ topic }}</a>
</p>

<p>Add a new note:</p>
<form action="{% url 'tasks:new_note' topic.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}
    <button name="submit">add note</button>
</form>

{% endblock content %}

tasks/templates/tasks/new_topic.html
{% extends 'tasks/layout.html' %} 

{% block content %}


<p>Add a new topic:</p>
<form action="{% url 'tasks:new_topic' %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}
    <button name="submit">add topic</button>
</form>

{% endblock content %}

tasks/templates/tasks/topic.html
{% extends 'tasks/layout.html' %} 


{% block content %}
<p>Task: {{ topic }}</p>
<p>Notes:</p>
<p>
    <a href="{% url 'tasks:new_note' topic.id %}">add new note</a>
</p>
<ul>
    {% for note in notes %}
    <li>
        <p>{{ note.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ note.text|linebreaks }}</p>
        <p><a href="{% url 'tasks:edit_note' note.id %}">edit note</a></p>
    </li>
    {% empty %}
    <li>
        There are no notes for this topic yet.
    </li>
    {% endfor %}
</ul>
{% endblock content %}

tasks/templates/tasks/topics.html
{% extends "tasks/layout.html" %} 

{% block content %}
<p>Tasks</p>

<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'tasks:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
    <li>No tasks have been added yet.</li>
    {% endfor %} 
</ul>

<a href="{% url 'tasks:new_topic' %}">Add a new task:</a>

{% endblock content %}